### 1. Obtener todos los hábitos (Prueba del Verbo GET)
GET http://localhost:5020/api/habitos
Accept: application/json

### 3. Probar validación con un nombre demasiado corto
POST http://localhost:5020/api/habitos
Content-Type: application/json

{
  "nombre": "Ir"
}
