### 1. Obtener todos los hábitos (Prueba del Verbo GET)
GET http://localhost:5020/api/habitos
Accept: application/json

### 3. Probar validación con un nombre demasiado corto
POST http://localhost:5020/api/habitos
Content-Type: application/json

{
  "nombre": "Ir"
}

### Consultar un hábito por ID
GET http://localhost:5020/api/habitos/4
Accept: application/json

### Actualizar un hábito por ID
PUT http://localhost:5020/api/habitos/4
Content-Type: application/json

{
  "nombre": "Hacer ejercicio diariamente"
}

### Eliminar un hábito por ID
DELETE http://localhost:5020/api/habitos/4